query FilteredProjects(
		$projectNumber: Int!,
		$area: [String], 
		$market: [String], 
		$priceFrom: Int, 
		$priceTo: Int,
		$bedroom: Int
		$bathroom: Int,
	){
	ProjectItems(
    per_page: $projectNumber,
    # filter_query: {
    #   __and: [
    #     { area: { in_array: $area } },
    #     { market: { in_array: $market } }
    #   ]
    # },
    filter_query_v2: {
    	area: { in_array: $area },
    	market: { in_array: $market }, 
    	price: { gt_int: $priceFrom , lt_int: $priceTo },
    	bedroom: { in_int: $bedroom },
    	bathroom: { in_int: $bathroom },
    },
    sort_by:"content.price:desc:int"
  ){
    total
		items {
      name
			content {
				area
				price
				market
        bedroom
        bathroom
			}
		}
	}
}
