query LatestProjects($projectNumber: Int!) {
    ProjectItems(per_page: $projectNumber) {
        items {
            name
            full_slug
            content {
                poster {
                    alt
                    filename
                }
                area
                price
                size
                bedroom
                bathroom
            }
        }
    }
}
