query LatestProjects($projectNumber: Int!) {
    ProjectItems(per_page: $projectNumber) {
        items {
            name
            full_slug
            content {
                poster {
                    alt
                    filename
                }
                area
                priceUSD
                sizeMeter
								sizeFeet
                bedroom
                bathroom
            }
        }
    }
}
