query Project($projectId: ID!) {
    ProjectItem(id: $projectId) {
        name
        content {
            poster {
                filename
                alt
            }
            gallery {
                filename
                alt
            }
						floorPlan {
                filename
                alt
            }
            mapLink
            imgMap {
                filename
                alt
            }
            price
            area
            adress
            buildingName
            sizeMeter
						sizeFeet
            bathroom
            bedroom
            description
            amenities
            facts
        }
    }
}
