query Project($projectId: ID!) {
    ProjectItem(id: $projectId) {
        name
        content {
            poster {
                filename
                alt
            }
            gallery {
                filename
                alt
            }
            prize
            area
            adress
            size
            bathroom
            bedroom
            description
            amenities
            facts
        }
    }
}
